version: '3'

services:
  service.medwatcher:
    image: swanseauniversity/medwatcher
    environment:
      - INPUT_DIR=./input
      - OUTPUT_DIR=./output
      - WATCH_PATTERN=medgate_entrypoint.py
    volumes:
      - ./:/usr/src/app
    command: "python /usr/src/app/watch.py"
